export { default as Home } from "./Home";
export { default as Employees } from "./Employees";
export { default as Attendance } from "./Attendance";
export { default as ManualAttendance } from "./ManualAttendance";
export { default as Registrations } from "./Registrations";
export { default as RegistrationForm } from "./RegistrationForm";
export { default as Holidays } from "./Holidays";
export { default as HolidayForm } from "./HolidayForm";
export { default as RequestedLeaves } from "./RequestedLeaves";
